# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iris.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\niris.proto\x12\x04iris\"j\n\x12IrisPredictRequest\x12\x14\n\x0csepal_length\x18\x01 \x01(\x02\x12\x13\n\x0bsepal_width\x18\x02 \x01(\x02\x12\x14\n\x0cpetal_length\x18\x03 \x01(\x02\x12\x13\n\x0bpetal_width\x18\x04 \x01(\x02\"L\n\x13IrisPredictResponse\x12\x0e\n\x06setosa\x18\x01 \x01(\x02\x12\x12\n\nversicolor\x18\x02 \x01(\x02\x12\x11\n\tvirginica\x18\x03 \x01(\x02\x62\x06proto3')



_IRISPREDICTREQUEST = DESCRIPTOR.message_types_by_name['IrisPredictRequest']
_IRISPREDICTRESPONSE = DESCRIPTOR.message_types_by_name['IrisPredictResponse']
IrisPredictRequest = _reflection.GeneratedProtocolMessageType('IrisPredictRequest', (_message.Message,), {
  'DESCRIPTOR' : _IRISPREDICTREQUEST,
  '__module__' : 'iris_pb2'
  # @@protoc_insertion_point(class_scope:iris.IrisPredictRequest)
  })
_sym_db.RegisterMessage(IrisPredictRequest)

IrisPredictResponse = _reflection.GeneratedProtocolMessageType('IrisPredictResponse', (_message.Message,), {
  'DESCRIPTOR' : _IRISPREDICTRESPONSE,
  '__module__' : 'iris_pb2'
  # @@protoc_insertion_point(class_scope:iris.IrisPredictResponse)
  })
_sym_db.RegisterMessage(IrisPredictResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IRISPREDICTREQUEST._serialized_start=20
  _IRISPREDICTREQUEST._serialized_end=126
  _IRISPREDICTRESPONSE._serialized_start=128
  _IRISPREDICTRESPONSE._serialized_end=204
# @@protoc_insertion_point(module_scope)
